
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_clone
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

  # security info
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URI}
  servlet:
    multipart:
      max-file-size: 50MB

# location to upload file
application:
  file:
    uploads:
      media-output-path: ./uploads

springdoc:
  default-produces-media-type: application/json

